version: '2'
services:
  caixa-eletronico:
    volumes:
      - ./:/app/
    container_name: caixa-eletronico
    image: caixa-eletronico
    build: ./

  caixa-eletronico-tests:
    image: php:7.4-alpine3.11
    volumes:
      - ./:/app/
    container_name: caixa-eletronico-tests

  composer:
    image: composer
    command: install --ignore-platform-reqs --prefer-dist -o
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/app